[package]
name = "minelaunch"
version = "0.1.2"
authors = ["Robert Fuchs <robertfuchsyoshi@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
flate2 = "1.0"
reqwest = "0.9.10"
tempfile = "3.0.7"
tar = "0.4"
